# Sponsorship Configuration for Stylos Scrapers

# Available sponsorship platforms
github: [erik172]          # GitHub Sponsors
# patreon: stylos-scrapers   # Patreon
# ko_fi: stylos_scrapers     # Ko-fi
# buymeacoffee: erik172      # Buy Me A Coffee

# Custom links
# custom: 
#   - https://github.com/erik172/stylos-scrapers
