# .bumpversion.toml
[tool.bumpversion]
current_version = "1.1.1"
commit = true
tag = true
message = "Bump version {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "stylos/__version__.py" 