# .bumpversion.toml
[tool.bumpversion]
current_version = "1.2.0"
commit = true
tag = true
message = "Bump version {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "stylos/__version__.py"

[[tool.bumpversion.files]]
filename = "README.md"
search = "[![Version](https://img.shields.io/badge/version-{current_version}-blue.svg)]"
replace = "[![Version](https://img.shields.io/badge/version-{new_version}-blue.svg)]" 

[[tool.bumpversion.files]]
filename = "README.md"
search = "### ✨ Nuevas Funcionalidades v{current_version}"
replace = "### ✨ Nuevas Funcionalidades v{new_version}"